version: "3.9"

services:

  mysql:
     image: mysql:8.0
     restart: always
     container_name: employee-manager-mysql
     networks:
       - employee-manager-network
     volumes:
       - $HOME/data/mysql/employee-manager:/var/lib/mysql
     env_file:
       - .env
     environment:
       MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
       MYSQL_DATABASE: $DB_NAME
       MYSQL_USER: $DB_USER
       MYSQL_PASSWORD: $DB_PASSWORD
     ports:
       - "$DB_PORT:$DB_PORT"

  adminer:
    image: adminer:4.8.1
    container_name: employee-manager-adminer
    depends_on:
      - mysql
    networks:
      - employee-manager-network
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    env_file:
      - .env

networks:
  employee-manager-network:
    driver: bridge